/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 x_-wing.glb 
Author: BlueMesh (https://sketchfab.com/VapTor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/x-wing-04b0147bd4234e61ba21bbf7a73ceecc
Title: X -WING
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Xwing(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/x_-wing.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.699}>
          <group name="Root">
            <group name="Plane" position={[0.312, -2.145, 0.464]}>
              <mesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials['Material.001']} />
            </group>
            <group name="Plane001" position={[0.312, -2.145, 0.464]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Plane001_0" geometry={nodes.Plane001_0.geometry} material={materials['Material.001']} />
            </group>
            <group name="Circle001" position={[0.312, -2.145, 0.464]} rotation={[Math.PI / 2, 0, 0.127]} scale={[0.159, 0.15, 0.15]}>
              <mesh name="Circle001_0" geometry={nodes.Circle001_0.geometry} material={materials['Material.001']} />
            </group>
            <group name="Circle" position={[0.312, -2.145, 0.464]} rotation={[Math.PI / 2, 0, 0]} scale={0.072}>
              <mesh name="Circle_0" geometry={nodes.Circle_0.geometry} material={materials['Material.001']} />
            </group>
            <group name="Circle002" position={[0.589, -2.157, 0.688]} rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
              <mesh name="Circle002_0" geometry={nodes.Circle002_0.geometry} material={materials.BakedCycles} />
            </group>
            <group name="Cube" position={[0, -0.935, 0.461]} scale={0.274}>
              <mesh name="Cube_0" geometry={nodes.Cube_0.geometry} material={materials['Material.001']} />
              <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.GLASS} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/x_-wing.glb')
